Vagrant.configure("2") do |config|

  config.vm.define :srv1 do |srv1|
    srv1.vm.box = "centos7"
    srv1.vm.network "private_network", ip:
    "192.168.86.200"
    end

  config.vm.define :srv2 do |srv2|
    srv2.vm.box = "centos7"
    srv2.vm.network "private_network", ip:
    "192.168.86.201"
  end
end

